### ISSUE TITLE
How can i add progress bar and duration in them generate canvas image ?

### ISSUE THREAD

**Issue by OOjai** [cstefFlexin/spotify-card#13]
![image](https://user-images.githubusercontent.com/68580646/235954632-7ecd84fe-4e6e-441b-b7e0-b843602d8168.png)

**Comment by cestef** [comment]
You can take a look at the options available here: https://github.com/cestef/spotify-card/blob/main/src/types/index.ts

You're probably looking for the `progressBar` option

**Comment by OOjai** [comment]
![image](https://user-images.githubusercontent.com/68580646/235959146-721a761f-023f-418f-b326-d36014402ba2.png)
![image](https://user-images.githubusercontent.com/68580646/235959571-50b4ad6a-c899-49f3-abc2-8fbe6ac243eb.png)

> You can take a look at the options available here: https://github.com/cestef/spotify-card/blob/main/src/types/index.ts
> 
> You're probably looking for the `progressBar` option

why it's not automatically fetching duration and progress bar.. i my above ss i am providing track and sourcename it's still not fetching `progressbar` and `duration`

**Comment by cestef** [comment]
As I said, you need to pass the progressBar related options, you are providing a youtube link, and there's no way to retrieve the player's positions from within the package being only given a link

**Comment by OOjai** [comment]
> As I said, you need to pass the progressBar related options, you are providing a youtube link, and there's no way to retrieve the player's positions from within the package being only given a link

can i have an example ? cuz your docs are not working so i am pretty confused how can i pass "progressBar related options" 
![image](https://user-images.githubusercontent.com/68580646/235977643-a5955c20-74f9-4f8a-a195-adbd61e923b8.png)
![image](https://user-images.githubusercontent.com/68580646/235978243-feb787c6-c814-4a17-9ccb-a8d3f303002b.png)


i am passing details but it's still not showing totalTime and current position in the generated canvas

**Comment by OOjai** [comment]
I fixed it thanks
