### ISSUE TITLE
Cannot Connect to Website on Firefox 94.0.1

### ISSUE THREAD

**Issue by zbj2** [cstefFlexin/spotify-card#5]
**How to reproduce?**
1. Have the latest version of Firefox
2. Visit [the website](https://spotify-card.cstef.dev/)

**Proof**
[Screenshot](https://imgur.com/a/KPvt2OK)

**Comment by cstefFlexin** [comment]
I forgot to update the website URL, sorry about that. the new one is https://docs.cstef.dev/docs/spotify-card
